name: Run the CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1

      - run: cargo clippy
      - run: cargo clippy --tests
      - run: cargo fmt --all -- --check
      - run: cargo test --all-features
      - run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
