name: Run the CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy check
        run: cargo clippy

      - name: Clippy check tests
        run: cargo clippy --tests

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  Doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Create doc
        run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features
